apiVersion: apps/v1
kind: Deployment
metadata:
  name: dta-consumer1db-deployment
  labels:
    type: consumer1db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     type: consumer1db-backend
  template:
    metadata:
      name: consumer1db-pod
      labels:
        apps: myapp
        type: consumer1db-backend
    spec:
      containers:
        - name: consumer1db-container
          image: pardha1024/dta-consumer1db
          ports:
            - containerPort: 7071
        