apiVersion: v1
kind: Service
metadata:
  name: dta-producer-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    type: producer-backend