apiVersion: v1
kind: Pod
metadata:
  name: dta-kafka-pod
  labels:
    apps: myapps
    type: kafka-pod
spec:
  containers:
  - name: kafka-container
    image: wurstmeister/kafka
    ports:
    - containerPort: 9093
    env:
      - name: KAFKA_LISTENERS
        value: INSIDE://0.0.0.0:9093
      - name: KAFKA_ADVERTISED_LISTENERS
        value: INSIDE://dta-kafka-service.default.svc.cluster.local:9093
      - name: KAFKA_LISTENER_PORT
        value: "9093"
      - name: KAFKA_LISTENER_NAME
        value: INSIDE_KAFKA_SERVICE
      - name: KAFKA_LISTENER_INTERFACE
        value: 0.0.0.0
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: dta-zookeeper-service:2181
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: INSIDE:PLAINTEXT
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL
        value: INSIDE:PLAINTEXT
      - name: KAFKA_LISTENER_NAME_INSIDE
        value: INSIDE
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: INSIDE  # This is the key fix to the error