apiVersion: v1
kind: Pod
metadata:
  name: dta-zookeeper-pod
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: zookeeper
      ports:
        - containerPort: 2181
      env:
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_LISTENER_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
      volumeMounts:
        - mountPath: /data
          name: zookeeper-storage
  restartPolicy: Always
  volumes:
    - name: zookeeper-storage
      emptyDir: {}