apiVersion: apps/v1
kind: Deployment
metadata:
  name: dta-consumer1-deployment
  labels:
    type: consumer1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
     type: consumer1-backend
  template:
    metadata:
      name: consumer1-pod
      labels:
        apps: myapp
        type: consumer1-backend
    spec:
      containers:
        - name: consumer1-container
          image: pardha1024/dta-consumer1
          ports:
            - containerPort: 8081
        